import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from "@/components/header"
import styles from "@/styles/MyDrops.module.scss"
import DropCardGrid from '@/components/dropCardGrid'

const inter = Inter({ subsets: ['latin'] })

export default function MyDrops () {
    return(
        <>
            <Head>
                <title>Nosso Clube</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={`${styles.main} ${inter.className}`}>
                <Header />
                
                <div className={styles.myDropsWrapper}>
                    <h1>Meus drops</h1>
                    <DropCardGrid />
                </div>
            </main>
        </>
    )
}