import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Login from '@/components/login'
import { useAccount } from "wagmi";
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { address } = useAccount()

  useEffect(() => {
    if (address) {
      console.log("connected wallet", address)
    }
  }, [address])
  
  return (
    <>
      <Head>
        <title>Reward ID</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <img src="/logo-vertical.png"/>
        <p>Olá, torcedor! Seja bem-vindo ao Reward ID.<br />Veja os drops que estão disponíveis para você, mesmo sem ter uma carteira crypto!</p>
        <Login />
      </main>
    </>
  )
}
